#!/bin/bash
echo "V1"

#Generating piget directory
mkdir /opt/piget
mkdir /opt/user

#User data directory
mkdir /opt/user/scripts
mkdir /opt/user/config
mkdir /opt/user/data

#We remove core functions if previously installed
rm -rf /opt/piget/core

#Cloning core scripts repository
git clone https://github.com/pigetnet/core /opt/piget/core

#Create link
if [ -f /net ];then
	rm /net
fi

if [ -f /pi ];then
	rm /pi
fi

if [ -f /show ];then
	rm /show
fi

if [ -f /string ];then
	rm /string
fi

if [ -f /system ];then
	rm /system
fi

if [ -f /do ];then
	rm /do
fi

ln -sv /opt/piget/core/net /net
ln -sv /opt/piget/core/pi /pi
ln -sv /opt/piget/core/show /show
ln -sv /opt/piget/core/string /string
ln -sv /opt/piget/core/system /system
ln -sv /opt/piget/ /do

/system/modifyBashStartup core
/pi/timeZone
echo "Updating package"
apt-get update

/show/description "PIGET WAS SUCCESFULLY INSTALLED"

if [ -f /boot/piget/scripts/postinstall.sh ]
	then
	/show/description "POST INSTALL SCRIPT FOUNDED"
	chmod +x /boot/piget/scripts/postinstall.sh
	/boot/piget/scripts/postinstall.sh
fi

